POST http://localhost:5000/api/volunteers/register
Content-Type: application/json

{
    "FullName": "LemLem Maharto",
    "email": "lemlem@gmail.com",
    "city": "tel aviv - yafo",
    "password": "500500500",
    "phoneNumber": "+9720503645592",
    "occupation": ["Food distribution"],
    "category": ["Immigrants"],
    "gender": "Female",
    "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPgp8ZtTbXi1_MWqsmKWDDaFIIPkNDExtyFw&usqp=CAU",
    "start": "11:00",
    "end": "14:00"
}

###

POST http://localhost:5000/register/volunteer
Content-Type: application/json

{
  "password":"12345678"
}


###
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "phoneNumber": "+972541234567",
    "occupation" : "Food distribution"
    
}

###
GET http://localhost:5000/api/data/fetch

###
GET http://localhost:5000/api/volunteers/volunteer/Lod/Gen

###
GET http://localhost:5000/api/volunteers/fetch

###
POST http://localhost:5000/api/volunteers/login
Content-Type: application/json

{
    "phoneNumber": "+97251212121",
    "password": "123452"
}

